runtime: nodejs22

instance_class: F1

env_variables:
  PORT: 8080
  NODE_ENV: production

automatic_scaling:
  min_instances: 1
  max_instances: 2
  target_cpu_utilization: 0.95

handlers:
- url: /assets
  static_dir: Client/static/assets
  secure: always

# 2. Handle the static HTML files (like login.html)
- url: /static
  static_dir: Client/static
  secure: always

# 3. Fallback to your Node.js server for everything else
- url: /.*
  script: auto
  secure: always
