events {
    worker_connections 1024;
}


http {
    # Define the rate limit zone in the http context
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;
    # (Optional) Change the default 503 status code to 429 Too Many Requests
    limit_req_status 429;


    server {
        listen 80;
        server_name localhost;
        limit_req zone=mylimit burst=20 nodelay;
        # return 301 https://$host$request_uri;
        location / {
            limit_req zone=mylimit burst=20 nodelay;
            proxy_pass http://web:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # server {
    #     listen 443 ssl;
    #     server_name your_domain.com www.your_domain.com; # Replace with your domain

    #     ssl_certificate /etc/nginx/ssl/your_domain.crt; # Path to your certificate file
    #     ssl_certificate_key /etc/nginx/ssl/your_domain.key; # Path to your private key file

    #     ssl_protocols TLSv1.3;

    #     location / {
    #         limit_req zone=mylimit burst=20 nodelay;
    #         proxy_pass http://localhost:5000/;
    #         proxy_set_header Host $host;
    #         proxy_set_header X-Real-IP $remote_addr;
    #         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #         proxy_set_header X-Forwarded-Proto $scheme;
    #     }

    # }

}

