runtime: nodejs24

instance_class: F1

env_variables:
  PORT: 8080
  NODE_ENV: production
  GCP_PROJECT_ID: boommywallet
  DB_TYPE: firestore

automatic_scaling:
  min_instances: 1
  max_instances: 1
  target_cpu_utilization: 0.95

handlers:
# For static handlers, the files must exists when the app is deployed, so we serve the built client files directly from the server's static directory.

# Fallback to your Node.js server for everything else
- url: /.*
  script: auto
  secure: always